test123: 88888888888888888888888888888
spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url : jdbc:mysql://192.168.90.41:3306/rt_blacklist?useUnicode=true&characterEncoding=utf-8
     username : root
     password : test@2017